# Learn more about configuring Gitpod here: https://www.gitpod.io/docs/introduction/learn-gitpod/gitpod-yaml
image:
  file: .gitpod/Dockerfile
tasks:
  - init: |
      cargo build
      cargo check
    command: cargo watch -x check
vscode:
  extensions:
  - bungcip.better-toml
  - rust-lang.rust-analyzer